### ISSUE TITLE
01

### ISSUE THREAD

**Issue by crabhi** [2016-molinf/Eda#1]
Ahoj,
je to fakt dobry! Jasný a čitelný. :+1:

**Comment by crabhi** [comment]
Jedna drobnost je, že pojmenovat proměnnou "slovnik" moc neřekne tomu, kdo to pak bude číst, ale je to drobnost, protože ostatní máš pojmenované podle významu.

**Comment by EdaEhler** [comment]
Díky,
ten "slovník" jsem si udělal pro sebe, vlastně jsem na nějakou čitelnost pro cizí moc nemyslel - ale je fakt, že i já sám bych měl po půl roce problémy s identifikací toho, co vlastně "slovník" ukládá za data...
